package sdk

import "errors"

var (
	ErrLicenseInvalid        = errors.New("license invalid")
	ErrLicenseExpired        = errors.New("license expired")
	ErrLicenseSuspended      = errors.New("license suspended")
	ErrMachineBanned         = errors.New("machine banned")
	ErrMaxMachinesExceeded   = errors.New("max machines exceeded")
	ErrProjectNotAuthorized  = errors.New("project not authorized")
	ErrBinaryNotRecognized   = errors.New("binary not recognized")
	ErrUpdateFrozen          = errors.New("update channel frozen")
	ErrNetworkError          = errors.New("network error")
	ErrInvalidServerResponse = errors.New("invalid server response")
	ErrNotActivated          = errors.New("guard not activated")
	ErrLocked                = errors.New("system locked: offline grace period expired")
	ErrBanned                = errors.New("system banned")
	ErrStateTampered         = errors.New("state tampered")
	ErrClockRollback         = errors.New("clock rollback detected")
	ErrLeaseBindingMismatch  = errors.New("lease machine binding mismatch")
	ErrLeaseUnavailable      = errors.New("valid lease unavailable")
	ErrHeartbeatInvalid      = errors.New("heartbeat response signature invalid")
	ErrHeartbeatNonceMismatch = errors.New("heartbeat response nonce mismatch")
	ErrTLSPinMismatch        = errors.New("tls spki pin mismatch")
	ErrTLSPinNotConfigured   = errors.New("tls spki pin not configured")
	ErrHardBindingUnavailable = errors.New("hard binding unavailable")
	ErrCDKNotFound           = errors.New("activation code not found")
	ErrCDKAlreadyUsed        = errors.New("activation code already used")
	ErrCDKRevoked            = errors.New("activation code revoked")
	ErrUpdateDownload        = errors.New("update download failed")
	ErrUpdateVerify          = errors.New("update verification failed")
	ErrUpdateApply           = errors.New("update apply failed")
	ErrUpdateRollback        = errors.New("update rollback failed")
	ErrUpdateDowngrade       = errors.New("ota target is not strictly newer than current version")
	ErrUpdateConcurrent      = errors.New("concurrent update not allowed")
	ErrPluginNotFound        = errors.New("plugin not found")
	ErrPluginNotManaged      = errors.New("plugin is not managed locally")
	ErrNoPluginUpdate        = errors.New("no plugin update available")
	ErrPluginOTADisabled     = errors.New("plugin ota is disabled")
)
