package sdk

import "errors"

var (
	ErrLicenseInvalid        = errors.New("license invalid")
	ErrLicenseExpired        = errors.New("license expired")
	ErrLicenseSuspended      = errors.New("license suspended")
	ErrMachineBanned         = errors.New("machine banned")
	ErrMaxMachinesExceeded   = errors.New("max machines exceeded")
	ErrProjectNotAuthorized  = errors.New("project not authorized")
	ErrUpdateFrozen          = errors.New("update channel frozen")
	ErrNetworkError          = errors.New("network error")
	ErrInvalidServerResponse = errors.New("invalid server response")
	ErrNotActivated          = errors.New("guard not activated")
	ErrLocked                = errors.New("system locked: offline grace period expired")
	ErrBanned                = errors.New("system banned")
	ErrCDKNotFound           = errors.New("activation code not found")
	ErrCDKAlreadyUsed        = errors.New("activation code already used")
	ErrCDKRevoked            = errors.New("activation code revoked")
	ErrUpdateDownload        = errors.New("update download failed")
	ErrUpdateVerify          = errors.New("update verification failed")
	ErrUpdateApply           = errors.New("update apply failed")
	ErrUpdateRollback        = errors.New("update rollback failed")
	ErrUpdateConcurrent      = errors.New("concurrent update not allowed")
	ErrPluginNotFound        = errors.New("plugin not found")
	ErrPluginNotManaged      = errors.New("plugin is not managed locally")
	ErrNoPluginUpdate        = errors.New("no plugin update available")
	ErrPluginOTADisabled     = errors.New("plugin ota is disabled")
)
